### ISSUE TITLE
Unit availability documentation error

### ISSUE THREAD

**Issue by captnconrad** [ait-energy/IESopt.jl#22]
In example available capacity should be at 70 electricity.
https://ait-energy.github.io/IESopt.jl/dev/pages/manual___reference/core_components/#IESopt.Unit

![grafik](https://github.com/user-attachments/assets/d1088ac7-2068-4206-9300-713352cbd7e0)

**Comment by sstroemer** [comment]
Since the docs CI run wasn't happy with the changes in Julia `v1.11`, the fix in 9ca3af1 wasn't actually deployed. Fixed in 1652bffd806eb0b6581fa0824e88faf8b6093965 and now visible in the dev version of the docs.
